/* eslint-disable @typescript-eslint/naming-convention,max-lines */

import type { InterviewStructure } from './types';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
// TODO
export const interviewStructure: InterviewStructure = {
  department: {
    recommendedDuration: 55,
    react: {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      react: {
        label: 'React',
        questionsNumber: 10,
        duration: 20,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    reactNative: {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      react: {
        label: 'React',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      reactNative: {
        label: 'React Native',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      nativePlatforms: {
        label: 'Native Platforms',
        questionsNumber: 2,
        duration: 4,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    angular: {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      angular: {
        label: 'Angular',
        questionsNumber: 10,
        duration: 20,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    vue: {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      vue: {
        label: 'Vue.js',
        questionsNumber: 10,
        duration: 20,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    node: {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      node: {
        label: 'Node.js',
        questionsNumber: 10,
        duration: 20,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    'react+node': {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      react: {
        label: 'React',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      node: {
        label: 'Node.js',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    'reactNative+node': {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 2,
        duration: 4,
        status: 'required',
      },
      react: {
        label: 'React',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      reactNative: {
        label: 'React Native',
        questionsNumber: 4,
        duration: 8,
        status: 'required',
      },
      nativePlatforms: {
        label: 'Native Platforms',
        questionsNumber: 2,
        duration: 4,
        status: 'required',
      },
      node: {
        label: 'Node.js',
        questionsNumber: 4,
        duration: 8,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    'angular+node': {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      angular: {
        label: 'Angular',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      node: {
        label: 'Node.js',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
    'vue+node': {
      javaScript: {
        label: 'JavaScript',
        questionsNumber: 7,
        duration: 14,
        status: 'required',
      },
      typeScript: {
        label: 'TypeScript',
        questionsNumber: 3,
        duration: 6,
        status: 'required',
      },
      vue: {
        label: 'Vue.js',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      node: {
        label: 'Node.js',
        questionsNumber: 5,
        duration: 10,
        status: 'required',
      },
      testing: {
        label: 'Testing',
        questionsNumber: 6,
        duration: 12,
        status: 'optional',
      },
      dataStructuresAndAlgorithms: {
        label: 'Data Structures And Algorithms',
        questionsNumber: 2,
        duration: 4,
        status: 'optional',
      },
      softwareSkills: {
        label: 'Software Skills',
        questionsNumber: 5,
        duration: 5,
        status: 'required',
      },
      testTasks: {
        label: 'Test Tasks',
        questionsNumber: 1,
        duration: 10,
        status: 'required',
      },
      experience: {
        label: 'Experience',
        questionsNumber: 3,
        duration: 6,
        status: 'optional',
      },
    },
  },
  // partnership: {},
};
