/* eslint-disable @typescript-eslint/naming-convention */

import type { Config } from '../src/types';

export const config: Config = {
  files: {
    questionsDatabasePath: 'data/questionsDB.html',
    notValidQuestionsFilename: 'notValidQuestions.txt',
    questionsFilename: 'questions.txt',
    pieChartFilename: 'pieChart.png',
    forInterviewerFilename: 'forInterviewer.pdf',
    resultDraftFilename: 'resultDraft.txt',
    resultNotesDraftFilename: 'resultNotesDraft.txt',
    radarChartFilename: 'radarChart.png',
    resultFilename: 'result.pdf',
    suitableQuestionMarker: '+ ',
  },
  pieChart: {
    width: 700,
    dataColors: [
      'rgb(254,74,73)',
      'rgb(42,183,202)',
      'rgb(254,215,102)',
      'rgb(246,171,182)',
      'rgb(0,91,150)',
      'rgb(123,192,67)',
      'rgb(243,119,54)',
      'rgb(79,55,45)',
      'rgb(255,119,170)',
      'rgb(74,78,77)',
    ],
    fontColor: 'rgb(74,78,77)',
    fontSize: 12,
    fontStyle: 'bold',
    centerFontSize: 32,
    dataFontColor: 'rgb(255, 255, 255)',
  },
  radarChart: {
    width: 700,
    datasetColor: 'rgb(0, 54, 167)',
    datasetBackgroundColor: 'rgba(0, 54, 167, 0.3)',
    fontSize: 10,
    fontColor: 'rgb(74,78,77)',
    fontStyle: 'bold',
    legendFontSize: 14,
    gridColor: 'rgb(187, 187, 187)',
    ticksBackgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  pdfDocument: {
    // paper
    creator: 'Dmitry Usik',
    author: 'Dmitry Usik',
    verticalMargin: 48,
    horizontalMargin: 48,
    // fonts
    regularFont: 'EBGaramond-Regular',
    regularFontPath: 'assets/fonts/EBGaramond-Regular.ttf',
    boldFont: 'EBGaramond-SemiBold',
    boldFontPath: 'assets/fonts/EBGaramond-SemiBold.ttf',
    smallerFontSize: 12,
    baseFontSize: 14,
    biggerFontSize: 18,
    biggestFontSize: 32,
    brandColor: [0, 54, 176],
    blackColor: [15, 15, 15],
    // icons
    riseappsLogoPath: 'assets/images/riseappsLogo.png',
    logoWidth: 80,
    logoMargin: 48,
    pieChartWidth: 360,
    radarChartWidth: 480,
    emailIconPath: 'assets/images/email.png',
    linkedinIconPath: 'assets/images/linkedin.png',
    userIconPath: 'assets/images/user.png',
    iconWidth: 20,
    // separator
    lineMargin: 8,
  },
  parsers: {
    topicKey: '@topic@',
    questionKey: '@questionKey@',
    feedbackKey: '@feedback@',
    decisionKey: '@decision@',
  },
  evaluation: {
    maxMark: 5,
    scale: {
      1: "Doesn't have theoretical and practical skills in this area.",
      2: 'Has superficial theoretical or practical skills in this area.',
      3: 'Has enough practice and superficial theoretical skills in this area.',
      4: 'Has good theoretical and practice skills in this area.',
      5: 'Has excellent theoretical and practice skills in this area.',
    },
  },
};
